/*
 * CIVIC (CivicNet) "civiclight" algorithm.
 * Copyright 2026 primo-arm-miner contributors (Ghuleh Miner additions).
 *
 * Initially written from a plain-language description of the algorithm's
 * steps. That first pass had a real bug (it skipped an intermediate SHA256
 * round before the XOR/yespower stage) which made every submitted share
 * come back "Low difficulty share". The combination logic below was
 * corrected against CivicLight's own published open-source CPU miner --
 * github.com/CivicLight/civiclight-miner-windows,
 * cpuminer-opt-source/algo/civiclight/civiclight.c -- which the project
 * explicitly states is open source (see civiclight.xyz/faq.html: "Everything
 * is open source at github.com/CivicLight, including the node/wallet, the
 * CPU miner, and this website"). See include/civiclight_algo.h for the
 * algorithm description. yespower itself -- the proof-of-work-heavy part of
 * civiclight v2 -- comes from its original authors' BSD-2 licensed reference
 * implementation, vendored unmodified at third_party/yespower/.
 *
 * This is the portable reference path (third_party/yespower/yespower-ref.c).
 * Like the project's other algorithms, an ARM NEON/asm-optimized path can
 * follow once this is validated correct and self-tests pass; nothing here
 * is a bottleneck-critical hot loop yet, so correctness came first.
 */
#include "civiclight_algo.h"
#include "miner.h"
#include "byteorder.h"

extern "C" {
#include "yespower.h"
#include "sha256.h"
}

#include <cstdio>
#include <cstring>
#include <pthread.h>

static pthread_mutex_t g_civic_lock = PTHREAD_MUTEX_INITIALIZER;
static bool g_civic_ready = false;

// ---------------------------------------------------------------------
// Core hash
// ---------------------------------------------------------------------

static void sha256d(const uint8_t *in, size_t len, uint8_t out[32])
{
    uint8_t round1[32];
    SHA256_Buf(in, len, round1);
    SHA256_Buf(round1, 32, out);
}

void civiclight_hash(const uint8_t header[80], uint32_t nTime, uint8_t out[32])
{
    uint8_t intermediate[32];
    sha256d(header, 80, intermediate);

    // Both v1 and v2 run the sha256d(header) result through one *more*
    // plain SHA256 before the XOR/yespower step -- this "hash1" stage was
    // missing here previously (we were XORing/feeding yespower with
    // `intermediate` directly), which is why every share came back "Low
    // difficulty share": our PoW hash never matched the network's for the
    // same header. Corrected against CivicLight's own published open-source
    // miner (github.com/CivicLight/civiclight-miner-windows,
    // cpuminer-opt-source/algo/civiclight/civiclight.c -- explicitly stated
    // open source at civiclight.xyz/faq.html) and verified offline against
    // a real solved CivicNet block (35998): this fixed pipeline produces a
    // hash under that block's actual PoW target; the previous one did not.
    uint8_t hash1[32];
    SHA256_Buf(intermediate, 32, hash1);

    if (nTime < CIVICLIGHT_V2_ACTIVATION_TIME) {
        // v1: XOR with the constant byte, then one more SHA256.
        uint8_t xored[32];
        for (int i = 0; i < 32; i++)
            xored[i] = hash1[i] ^ 0x5A;
        SHA256_Buf(xored, 32, out);
        return;
    }

    // v2: yespower(hash1, N=2048, r=8), XOR against hash1, then one more
    // SHA256.
    yespower_local_t local;
    yespower_init_local(&local);

    yespower_params_t params;
    params.version = YESPOWER_1_0;
    params.N = CIVICLIGHT_YESPOWER_N;
    params.r = CIVICLIGHT_YESPOWER_R;
    params.pers = nullptr;
    params.perslen = 0;

    yespower_binary_t yhash;
    yespower(&local, hash1, 32, &params, &yhash);
    yespower_free_local(&local);

    uint8_t xored[32];
    for (int i = 0; i < 32; i++)
        xored[i] = yhash.uc[i] ^ hash1[i];
    SHA256_Buf(xored, 32, out);
}

// ---------------------------------------------------------------------
// Self-test
//
// These are not CivicLight's own test vectors -- they're generated by
// running the corrected civiclight_hash() above (see the provenance note
// at the top of this file) against a deterministic local test header, using
// this build's own SHA256 and the vendored (BSD-2) yespower reference
// implementation. If a future NEON/asm path is added for either sha256 or
// yespower here, these vectors are what must keep matching.
// ---------------------------------------------------------------------

static bool hex_eq(const uint8_t *bin, const char *hex)
{
    char buf[65];
    for (int i = 0; i < 32; i++)
        snprintf(buf + i * 2, 3, "%02x", bin[i]);
    buf[64] = '\0';
    return strcmp(buf, hex) == 0;
}

int civiclight_init_runtime(int n_threads)
{
    (void)n_threads;

    pthread_mutex_lock(&g_civic_lock);

    // Deterministic 80-byte test header: bytes 0..79.
    uint8_t header[80];
    for (int i = 0; i < 80; i++)
        header[i] = (uint8_t)i;

    uint8_t out[32];

    // v1 (nTime below activation)
    civiclight_hash(header, CIVICLIGHT_V2_ACTIVATION_TIME - 1, out);
    if (!hex_eq(out, "8a086ae422e9a23a5c6c917887350108c712bd7e295a331bd5caf25a1a535f89")) {
        applog(LOG_ERR, "civiclight self-test FAILED (v1 vector mismatch) -- refusing to mine");
        pthread_mutex_unlock(&g_civic_lock);
        return 0;
    }

    // v2 (nTime at/after activation)
    civiclight_hash(header, CIVICLIGHT_V2_ACTIVATION_TIME, out);
    if (!hex_eq(out, "792bbe18ad67c99128c6a18f00e20ef2b3557fd1f7dee26f9382f5d852520680")) {
        applog(LOG_ERR, "civiclight self-test FAILED (v2/yespower vector mismatch) -- refusing to mine");
        pthread_mutex_unlock(&g_civic_lock);
        return 0;
    }

    g_civic_ready = true;
    applog(LOG_INFO, "civiclight self-test passed");
    pthread_mutex_unlock(&g_civic_lock);
    return 1;
}

void civiclight_cleanup_runtime(void)
{
    g_civic_ready = false;
}

// ---------------------------------------------------------------------
// Mining loop
// ---------------------------------------------------------------------

int scanhash_civic(int thr_id, struct work *work, uint32_t max_hashes,
                    unsigned long *hashes_done)
{
    (void)thr_id;

    uint32_t *pdata = work->data;
    uint32_t *ptarget = work->target;
    uint8_t header[80];
    uint32_t n = pdata[19];   // nonce, word 19 (byte 76)
    uint32_t first_nonce = n;
    uint32_t nTime;

    work->valid_nonces = 0;

    // build_standard_work() (src/stratum_standard.cpp) populates every word
    // of pdata[0..18] uniformly via le32dec() of the raw job/header bytes
    // (version, prevhash, merkle root, nTime, nBits all go through
    // le32dec -- see build_standard_work()'s new_work->data[...] = le32dec(...)
    // assignments). le32dec/le32enc are exact inverses, so reconstructing the
    // true 80-byte header here requires le32enc on *every* word, not just
    // the merkle-root words.
    //
    // This function used to copy scanhash_sha256d's be32enc-for-most-words
    // pattern (see git history), on the assumption it was "the real header
    // byte order" convention shared across algorithms. It isn't: that
    // pattern exists because scanhash_sha256d's own optimized SHA256 routine
    // wants its input pre-arranged for its internal hot loop, not because
    // it's the literal serialized header. civiclight_hash() calls a plain
    // generic SHA256_Buf() with no such compensating internal swap, so it
    // needs the literal, standard little-endian header bytes -- confirmed
    // by reconstructing a real solved CivicNet block's header this same way
    // and finding be32enc-for-those-words produced a completely different
    // (wrong) header than the real one, while all-le32enc matched exactly.
    // This was the actual reason every share came back "Low difficulty
    // share" even after fixing the hash-combination logic itself: we were
    // hashing the wrong bytes.
    for (int i = 0; i < 19; i++)
        le32enc(header + i * 4, pdata[i]);
    le32enc(header + 76, pdata[19]);

    nTime = pdata[17];

    uint32_t remaining = max_hashes;
    while (remaining > 0 &&
           !miner_work_restart_requested(work->restart_generation) &&
           !miner_should_abort()) {
        le32enc(header + 76, n);

        uint8_t hash[32];
        civiclight_hash(header, nTime, hash);

        // hash[] is a standard big-endian SHA256 digest (word i's bytes at
        // hash[i*4..i*4+3], big-endian). hash_le_target wants each word
        // byte-swapped in place (same convention as scanhash_sha256d's
        // hash_le), not word-order reversed -- le32dec on the same offset
        // does exactly that swap.
        uint32_t hash_le[8];
        for (int i = 0; i < 8; i++)
            hash_le[i] = le32dec(hash + i * 4);

        if (hash_le_target(hash_le, ptarget)) {
            pdata[19] = n;
            work->nonces[work->valid_nonces] = n;
            bn_store_share_difficulty(hash_le, ptarget, work, work->valid_nonces);
            applog(LOG_INFO, "civiclight: Found nonce %08x!", n);
            work->valid_nonces++;
            if (work->valid_nonces >= MAX_NONCES)
                break;
        }

        n++;
        remaining--;
    }

    *hashes_done = n - first_nonce;
    pdata[19] = n;
    return work->valid_nonces;
}
